bits/siginfo-consts.h: enum definition for TRAP_HWBKPT is missing
Compile following linux kernel test code with latest glibc:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/breakpoints/breakpoint_test_arm64.c

and we get following error:
breakpoint_test_arm64.c: In function ‘run_test’:
breakpoint_test_arm64.c:171:25: error: ‘TRAP_HWBKPT’ undeclared (first use in this function)
  if (siginfo.si_code != TRAP_HWBKPT) {
                         ^
I can compile test code by modifying my local
/usr/include/bits/siginfo.h and test works great. Therefore, this patch
will be needed in upstream glibc so that issue is fixed there as well.

Signed-off-by: Pratyush Anand <panand@redhat.com>

Upstream-Status: Submitted [https://sourceware.org/bugzilla/show_bug.cgi?id=21286]